[package]
name = "pz"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.9"

[dependencies.bumpalo]
version = "3.12.1"
features = ["collections"]

[dev-dependencies]
googletest = "0.5.0"
unindent = "0.2.1"

[build-dependencies]
prost-build = "0.11.9"